sudo: false
language: java
jdk: oraclejdk8

cache:
  directories:
  - "$HOME/.cache"

deploy:
  provider: script
  script: 
    - cd fms-config
    - mvn clean install -DskipTests
  skip_cleanup: true
  on:
    tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
