sudo: required
language: java
jdk: oraclejdk8
install: true

cache:
  directories:
  - "$HOME/.cache"

deploy:
  provider: script
  script: 
    - cd fms-config
    - mvn clean install -DskipTests
after_success:
  - bash <(curl -s https://codecov.io/bash)
